version: '3.9'

services:
  catalog-svc_1:
    build: ./catalog-svc
    ports:
      - "6543:5000"
    volumes:
      - ./catalog-svc:/root/app

  shop-front:
    build: ./shop-front-svc
    ports:
      - "6544:5000"
    volumes:
      - ./shop-front-svc:/root/app

  product-admin:
    build: ./product-admin-svc
    ports:
      - "6545:5000"
    volumes:
      - ./product-admin-svc:/root/app

  song-player:
    build: ./song-player-svc
    ports:
      - "6546:5000"
    volumes:
      - ./song-player-svc:/root/app

  history:
    build: ./history-svc
    ports:
      - "6548:5000"
    volumes:
      - ./history-svc:/root/app

  song-player-nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./product-admin-svc/song-locations/:/usr/share/nginx/html


  gateway:
    image: nginx:latest
    ports:
      - "85:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  login-page:
    build: ./login-page-svc
    ports:
      - "6547:5000"
    volumes:
      - ./login-page-svc:/root/app

  #catalog-db uses redis
  catalog-db:
    image: redis
    ports:
      - "6379:6379"

  #login-db uses redis for user storage
  login-db:
    image: redis
    ports:
      - "6380:6379"