user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include /etc/nginx/mime.types;
    client_max_body_size 8M;
    default_type application/octet-stream;

    server {
        listen       80;
        client_max_body_size 8M;
        server_name  localhost;

        # Route for shop front page
        location / {
            proxy_pass http://shop-front:5000/get-catalog;
        }

        # Route for catalog data
        location /get-catalog {
            proxy_pass http://shop-front:5000/get-catalog;
        }

        # Route for product admin form page
        location /add-product-page {
            proxy_pass http://product-admin:5000/add-product-page;
        }

        # Route for adding products
        location /add-product {
            proxy_pass http://product-admin:5000/add-product;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}