user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include /etc/nginx/mime.types;
    client_max_body_size 8M;
    default_type application/octet-stream;

    server {
        listen       80;
        client_max_body_size 8M;
        server_name  localhost;

        # Route for shop front page
        location / {
            proxy_pass http://shop-front:5000/get-catalog;
        }

        # Route for catalog data
        location /get-catalog {
            proxy_pass http://shop-front:5000/get-catalog;
        }

        # Route for product admin form page
        location /add-product-page {
            proxy_pass http://product-admin:5000/add-product-page;
        }

        # Route for adding products
        location /add-product {
            proxy_pass http://product-admin:5000/add-product;
        }

        # Route for song player - list all songs or play specific song
        # Handles both /play-songs and /play-songs/filename.mp3
        location /play-songs {
            proxy_pass http://song-player:5000/play-songs;
        }

        # Route for login page
        location /login-page {
            proxy_pass http://login-page:5000/login-page;
        }

        # Route for login action
        location /login {
            proxy_pass http://login-page:5000/login;
        }

        # Route for signup action
        location /signup {
            proxy_pass http://login-page:5000/signup;
        }

        # Route for logout action
        location /logout {
            proxy_pass http://login-page:5000/logout;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}