FROM python:3.12.0

WORKDIR /root
RUN pip install --upgrade pip
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt
WORKDIR /root/app
COPY . .
WORKDIR /root

CMD ["python", "app/history-page.py"]
