apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-db-depl
  template:
    metadata:
      labels:
        app: login-db-depl
    spec:
      containers:
      - name: login-db
        image: redis:8.6
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
